export const LOADER = 'LOADER';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_RESPONSE = 'GET_PRODUCT_RESPONSE';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_RESPONSE = 'ADD_PRODUCT_RESPONSE';
